version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@7
      - run:
          name: Install localization tool
          command: sudo npm install -g i18nexus-cli
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Format
          command: yarn prettier
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
